# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.srcs/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/baseDesign_dram_test_0_0.xci
# IP: The module: 'baseDesign_dram_test_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_data_fifo/mmap_data_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] -quiet

# IP: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_request_fifo/mmap_request_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_data_fifo/mmap_data_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_data_fifo/mmap_data_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_request_fifo/mmap_request_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_request_fifo/mmap_request_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.srcs/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/baseDesign_dram_test_0_0.xci
# IP: The module: 'baseDesign_dram_test_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_data_fifo/mmap_data_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] -quiet

# IP: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_request_fifo/mmap_request_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_data_fifo/mmap_data_fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_data_fifo/mmap_data_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_request_fifo/mmap_request_fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/ip/baseDesign_dram_test_0_0/src/mmap_request_fifo/mmap_request_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
