# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/emmet/Desktop/Convolution/ip_repo/dram_test_1.0/src/mmap_data_fifo/mmap_data_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] -quiet

# IP: c:/Users/emmet/Desktop/Convolution/ip_repo/dram_test_1.0/src/mmap_request_fifo/mmap_request_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] -quiet

# XDC: c:/users/emmet/desktop/convolution/convolution.tmp/dram_test_v1_0_project/dram_test_v1_0_project.gen/sources_1/ip/mmap_data_fifo/mmap_data_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/users/emmet/desktop/convolution/convolution.tmp/dram_test_v1_0_project/dram_test_v1_0_project.gen/sources_1/ip/mmap_data_fifo/mmap_data_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/users/emmet/desktop/convolution/convolution.tmp/dram_test_v1_0_project/dram_test_v1_0_project.gen/sources_1/ip/mmap_request_fifo/mmap_request_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/users/emmet/desktop/convolution/convolution.tmp/dram_test_v1_0_project/dram_test_v1_0_project.gen/sources_1/ip/mmap_request_fifo/mmap_request_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
