# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/baseDesign/baseDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baseDesign || ORIG_REF_NAME==baseDesign} -quiet] -quiet

# IP: bd/baseDesign/ip/baseDesign_processing_system7_0_0/baseDesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baseDesign_processing_system7_0_0 || ORIG_REF_NAME==baseDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/baseDesign/ip/baseDesign_dram_test_0_0/baseDesign_dram_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baseDesign_dram_test_0_0 || ORIG_REF_NAME==baseDesign_dram_test_0_0} -quiet] -quiet

# IP: bd/baseDesign/ip/baseDesign_clk_wiz_0_0/baseDesign_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baseDesign_clk_wiz_0_0 || ORIG_REF_NAME==baseDesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/baseDesign/ip/baseDesign_ps7_0_axi_periph_0/baseDesign_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baseDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==baseDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/baseDesign/ip/baseDesign_rst_ps7_0_100M_0/baseDesign_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baseDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==baseDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/baseDesign/ip/baseDesign_auto_pc_0/baseDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baseDesign_auto_pc_0 || ORIG_REF_NAME==baseDesign_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/johnn/Documents/School/reconfig/Convolution/Convolution.gen/sources_1/bd/baseDesign/baseDesign_ooc.xdc
